<?php

namespace ContainerIIhv7Rh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xj_FVVUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xj.FVVU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xj.FVVU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emi' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mlr' => ['privates', 'App\\Repository\\MediaListRepository', 'getMediaListRepositoryService', true],
            'mediaListManager' => ['privates', 'App\\Service\\MediaListManager', 'getMediaListManagerService', true],
        ], [
            'emi' => '?',
            'mlr' => 'App\\Repository\\MediaListRepository',
            'mediaListManager' => 'App\\Service\\MediaListManager',
        ]);
    }
}
