<?php

namespace ContainerIIhv7Rh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArchMediaListControllerarchiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RG6Wi7B.App\Controller\ArchMediaListController::archive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RG6Wi7B.App\\Controller\\ArchMediaListController::archive()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mlr' => ['privates', 'App\\Repository\\MediaListRepository', 'getMediaListRepositoryService', true],
            'mediaListManager' => ['privates', 'App\\Service\\MediaListManager', 'getMediaListManagerService', true],
        ], [
            'mlr' => 'App\\Repository\\MediaListRepository',
            'mediaListManager' => 'App\\Service\\MediaListManager',
        ]))->withContext('App\\Controller\\ArchMediaListController::archive()', $container);
    }
}
