<?php

namespace ContainerIIhv7Rh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteMediaListControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xj.FVVU.App\Controller\DeleteMediaListController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xj.FVVU'] ?? $container->load('get_ServiceLocator_Xj_FVVUService'));

        if (isset($container->privates['.service_locator.xj.FVVU.App\\Controller\\DeleteMediaListController::delete()'])) {
            return $container->privates['.service_locator.xj.FVVU.App\\Controller\\DeleteMediaListController::delete()'];
        }

        return $container->privates['.service_locator.xj.FVVU.App\\Controller\\DeleteMediaListController::delete()'] = $a->withContext('App\\Controller\\DeleteMediaListController::delete()', $container);
    }
}
