<?php

namespace ContainerIIhv7Rh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditMediaListControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xj.FVVU.App\Controller\EditMediaListController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xj.FVVU.App\\Controller\\EditMediaListController::edit()'] = ($container->privates['.service_locator.xj.FVVU'] ?? $container->load('get_ServiceLocator_Xj_FVVUService'))->withContext('App\\Controller\\EditMediaListController::edit()', $container);
    }
}
