<?php

namespace ContainerIIhv7Rh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FileManager' shared autowired service.
     *
     * @return \App\Service\FileManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FileManager.php';

        return $container->privates['App\\Service\\FileManager'] = new \App\Service\FileManager();
    }
}
