<?php

namespace ContainerIIhv7Rh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaListManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MediaListManager' shared autowired service.
     *
     * @return \App\Service\MediaListManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MediaListManager.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ProcessExecutor.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\MediaListManager'])) {
            return $container->privates['App\\Service\\MediaListManager'];
        }

        return $container->privates['App\\Service\\MediaListManager'] = new \App\Service\MediaListManager(new \App\Service\ProcessExecutor(), ($container->privates['App\\Service\\FileManager'] ??= new \App\Service\FileManager()), $a, \dirname(__DIR__, 4));
    }
}
