<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElJHP3K\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElJHP3K/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerElJHP3K.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerElJHP3K\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerElJHP3K\App_KernelProdContainer([
    'container.build_hash' => 'ElJHP3K',
    'container.build_id' => 'c92ef28d',
    'container.build_time' => 1734269189,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerElJHP3K');
