<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'index.archived' => [[], ['_controller' => 'App\\Controller\\ArchivedIndexController::index'], [], [['text', '/archivedIndex']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'show.mediaList' => [['id'], ['_controller' => 'App\\Controller\\MediaListController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/mediaList']], [], [], []],
    'App\Controller\ArchivedIndexController::index' => [[], ['_controller' => 'App\\Controller\\ArchivedIndexController::index'], [], [['text', '/archivedIndex']], [], [], []],
    'App\Controller\IndexController::index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\MediaListController::show' => [['id'], ['_controller' => 'App\\Controller\\MediaListController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/mediaList']], [], [], []],
];
