<?php

namespace ContainerRx007wn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditMediaListControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c_x.wAL.App\Controller\EditMediaListController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c_x.wAL.App\\Controller\\EditMediaListController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emi' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mlr' => ['privates', 'App\\Repository\\MediaListRepository', 'getMediaListRepositoryService', true],
        ], [
            'emi' => '?',
            'mlr' => 'App\\Repository\\MediaListRepository',
        ]))->withContext('App\\Controller\\EditMediaListController::edit()', $container);
    }
}
