<?php

namespace ContainerElJHP3K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArchivedIndexController::index' => ['privates', '.service_locator.cKEcjF9.App\\Controller\\ArchivedIndexController::index()', 'getArchivedIndexControllerindexService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.cKEcjF9.App\\Controller\\IndexController::index()', 'getIndexControllerindexService', true],
            'App\\Controller\\MediaListController::show' => ['privates', '.service_locator.cKEcjF9.App\\Controller\\MediaListController::show()', 'getMediaListControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArchivedIndexController:index' => ['privates', '.service_locator.cKEcjF9.App\\Controller\\ArchivedIndexController::index()', 'getArchivedIndexControllerindexService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.cKEcjF9.App\\Controller\\IndexController::index()', 'getIndexControllerindexService', true],
            'App\\Controller\\MediaListController:show' => ['privates', '.service_locator.cKEcjF9.App\\Controller\\MediaListController::show()', 'getMediaListControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArchivedIndexController::index' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\MediaListController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArchivedIndexController:index' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\MediaListController:show' => '?',
        ]));
    }
}
