<?php

namespace ContainerElJHP3K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArchivedIndexControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ArchivedIndexController' shared autowired service.
     *
     * @return \App\Controller\ArchivedIndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ArchivedIndexController'] = $instance = new \App\Controller\ArchivedIndexController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ArchivedIndexController', $container));

        return $instance;
    }
}
