<?php

namespace ContainerElJHP3K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.cKEcjF9.App\Controller\IndexController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cKEcjF9.App\\Controller\\IndexController::index()'] = ($container->privates['.service_locator.cKEcjF9'] ?? $container->load('get_ServiceLocator_CKEcjF9Service'))->withContext('App\\Controller\\IndexController::index()', $container);
    }
}
