<?php

namespace ContainerElJHP3K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaListRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MediaListRepository' shared autowired service.
     *
     * @return \App\Repository\MediaListRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MediaListRepository'] = new \App\Repository\MediaListRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
