<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MediaList extends \App\Entity\MediaList implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archived' => [parent::class, 'archived', null],
        "\0".parent::class."\0".'cronjob' => [parent::class, 'cronjob', null],
        "\0".parent::class."\0".'delete_after' => [parent::class, 'delete_after', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'path' => [parent::class, 'path', null],
        "\0".parent::class."\0".'quality' => [parent::class, 'quality', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'url' => [parent::class, 'url', null],
        "\0".parent::class."\0".'x_last_videos' => [parent::class, 'x_last_videos', null],
        'archived' => [parent::class, 'archived', null],
        'cronjob' => [parent::class, 'cronjob', null],
        'delete_after' => [parent::class, 'delete_after', null],
        'id' => [parent::class, 'id', null],
        'path' => [parent::class, 'path', null],
        'quality' => [parent::class, 'quality', null],
        'title' => [parent::class, 'title', null],
        'type' => [parent::class, 'type', null],
        'url' => [parent::class, 'url', null],
        'x_last_videos' => [parent::class, 'x_last_videos', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
